<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArthurKamsu.S2S.Oauth.Clientcredentials.Core\ArthurKamsu.S2S.Oauth.Clientcredentials.Core.csproj" />
  </ItemGroup>

</Project>
